### ISSUE TITLE
Bug in Sonata I2C header

### ISSUE THREAD

**Issue by djlowther** [microsoft/cheriot-rtos#274]
In `sunburst/platform-i2c.hh`, line 397, `interrupt_clear()` is implemented as

```
interruptState = interruptState & ~interrupt_bit(interrupt);
```

Paradoxically, this statement actually clears all active interrupts _except_ the specified interrupt, because `INTR_STATE` is an `rw1c` register. To clear only the specified interrupt, the line in question should be

```
interruptState = interrupt_bit(interrupt);
```

**Comment by HU90m** [comment]
Ah whoops, it looks like you're spot on. Are you happy to open a PR?

**Comment by djlowther** [comment]
Opened PR #276 .
